name: colab
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.6.7
    - numpy==1.14.6
    - matplotlib
    - jupyter
    - opencv
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - ffmpeg
    - imageio
    - pyqt
    - pip:
        - moviepy
        - tensorflow==1.12.0
        - keras==2.2.4
